# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xiugai.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import bj1
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem,QMessageBox
from denglu import Ui_MainWindow
from connect import *

cursor,conn=connect()

class dengluui(QtWidgets.QMainWindow,Ui_MainWindow):
    def __init__(self, parent=None):
        super(dengluui, self).__init__(parent)
        self.setupUi(self)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 615)
        Form.setStyleSheet("")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 861, 621))
        self.listWidget.setStyleSheet("border-image: url(:/西工大.jpg);")
        self.listWidget.setObjectName("listWidget")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 120, 591, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xh = QtWidgets.QLineEdit(self.layoutWidget)
        self.xh.setMinimumSize(QtCore.QSize(0, 40))
        self.xh.setStyleSheet("QLineEdit {\n"
"background-color: rgba(255, 255,255,0);\n"
"border:none;\n"
"border-bottom:1px solid black\n"
"}")
        self.xh.setObjectName("xh")
        self.verticalLayout.addWidget(self.xh)
        self.omm = QtWidgets.QLineEdit(self.layoutWidget)
        self.omm.setMinimumSize(QtCore.QSize(0, 40))
        self.omm.setSizeIncrement(QtCore.QSize(0, 40))
        self.omm.setStyleSheet("QLineEdit {\n"
"background-color: rgba(255, 255,255,0);\n"
"border:none;\n"
"border-bottom:1px solid black\n"
"}")
        self.omm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.omm.setObjectName("omm")
        self.verticalLayout.addWidget(self.omm)
        self.nmm = QtWidgets.QLineEdit(self.layoutWidget)
        self.nmm.setMinimumSize(QtCore.QSize(0, 40))
        self.nmm.setSizeIncrement(QtCore.QSize(0, 40))
        self.nmm.setStyleSheet("QLineEdit {\n"
"background-color: rgba(255, 255,255,0);\n"
"border:none;\n"
"border-bottom:1px solid black\n"
"}")
        self.nmm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.nmm.setObjectName("nmm")
        self.verticalLayout.addWidget(self.nmm)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 50, 371, 51))
        self.label.setObjectName("label")
        self.tc = QtWidgets.QPushButton(Form)
        self.tc.setGeometry(QtCore.QRect(700, 40, 111, 41))
        self.tc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tc.setObjectName("tc")
        self.qd = QtWidgets.QPushButton(Form)
        self.qd.setGeometry(QtCore.QRect(310, 510, 221, 71))
        self.qd.setObjectName("qd")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.qd.clicked.connect(self.changemm)
        self.tc.clicked.connect(self.exite)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.xh.setPlaceholderText(_translate("Form", "学号："))
        self.omm.setPlaceholderText(_translate("Form", "旧密码："))
        self.nmm.setPlaceholderText(_translate("Form", "新密码："))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; color:#ff0000;\">请输入正确的信息以修改密码</span></p></body></html>"))
        self.tc.setText(_translate("Form", "退出"))
        self.qd.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.qd.setText(_translate("Form", "确定"))

    def changemm(self):
        readernumber = self.xh.text()
        password1 = self.omm.text()
        password2 = self.nmm.text()
        sql = 'SELECT * FROM reader WHERE ID号 = "%s"' % readernumber
        res = cursor.execute(sql)
        if res:
            sql1 = 'SELECT * FROM reader WHERE password = %s and ID号="%s"'% (password1, readernumber)
            res = cursor.execute(sql1)
            if res:
                sql2 = 'update reader set password = "%s" where ID号="%s"'% (password2, readernumber)
                cursor.execute(sql2)
                conn.commit()
                QMessageBox.warning(self, "提示", "修改成功！", QMessageBox.Yes)
            else:
                QMessageBox.warning(self, "警告", "旧密码错误！", QMessageBox.Yes)
        else:
            QMessageBox.warning(self, "警告", "该读者ID不存在！", QMessageBox.Yes)

    def exite(self):
        self.denglu1 = dengluui()
        self.denglu1.show()
        self.close()

