# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhuceduzhe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem,QMessageBox
from denglu import Ui_MainWindow
from connect import *

cursor,conn=connect()

class dengluui(QtWidgets.QMainWindow,Ui_MainWindow):
    def __init__(self, parent=None):
        super(dengluui, self).__init__(parent)
        self.setupUi(self)

class Ui_zhuce1(object):
    def setupUi(self, zhuce1):
        zhuce1.setObjectName("zhuce1")
        zhuce1.resize(712, 524)
        zhuce1.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton = QtWidgets.QPushButton(zhuce1)
        self.pushButton.setGeometry(QtCore.QRect(250, 410, 221, 81))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(zhuce1)
        self.label.setGeometry(QtCore.QRect(60, 40, 251, 51))
        self.label.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(zhuce1)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 100, 613, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sm = QtWidgets.QLineEdit(self.layoutWidget)
        self.sm.setMinimumSize(QtCore.QSize(300, 40))
        self.sm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sm.setText("")
        self.sm.setObjectName("sm")
        self.verticalLayout.addWidget(self.sm)
        self.xy = QtWidgets.QLineEdit(self.layoutWidget)
        self.xy.setMinimumSize(QtCore.QSize(300, 40))
        self.xy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xy.setText("")
        self.xy.setObjectName("xy")
        self.verticalLayout.addWidget(self.xy)
        self.xb = QtWidgets.QComboBox(self.layoutWidget)
        self.xb.setMinimumSize(QtCore.QSize(300, 40))
        self.xb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xb.setObjectName("xb")
        self.xb.addItem("")
        self.xb.addItem("")
        self.verticalLayout.addWidget(self.xb)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.xm = QtWidgets.QLineEdit(self.layoutWidget)
        self.xm.setMinimumSize(QtCore.QSize(300, 40))
        self.xm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xm.setText("")
        self.xm.setObjectName("xm")
        self.verticalLayout_2.addWidget(self.xm)
        self.dh = QtWidgets.QLineEdit(self.layoutWidget)
        self.dh.setMinimumSize(QtCore.QSize(300, 40))
        self.dh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dh.setText("")
        self.dh.setObjectName("dh")
        self.verticalLayout_2.addWidget(self.dh)
        self.lx = QtWidgets.QComboBox(self.layoutWidget)
        self.lx.setMinimumSize(QtCore.QSize(300, 40))
        self.lx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lx.setObjectName("lx")
        self.lx.addItem("")
        self.lx.addItem("")
        self.lx.addItem("")
        self.verticalLayout_2.addWidget(self.lx)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.mm = QtWidgets.QLineEdit(zhuce1)
        self.mm.setGeometry(QtCore.QRect(210, 350, 300, 40))
        self.mm.setMinimumSize(QtCore.QSize(300, 40))
        self.mm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mm.setText("")
        self.mm.setObjectName("mm")
        self.pushButton2 = QtWidgets.QPushButton(zhuce1)
        self.pushButton2.setGeometry(QtCore.QRect(570, 27, 111, 41))
        self.pushButton2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton2.setObjectName("pushButton2")

        self.retranslateUi(zhuce1)
        QtCore.QMetaObject.connectSlotsByName(zhuce1)
        self.pushButton.clicked.connect(self.insert)
        self.pushButton2.clicked.connect(self.exite)

    def retranslateUi(self, zhuce1):
        _translate = QtCore.QCoreApplication.translate
        zhuce1.setWindowTitle(_translate("zhuce1", "Form"))
        self.pushButton.setText(_translate("zhuce1", "注册"))
        self.label.setText(_translate("zhuce1", "<html><head/><body><p><span style=\" font-size:16pt; color:#ff0000;\">请输入相关的信息</span></p></body></html>"))
        self.sm.setPlaceholderText(_translate("zhuce1", "ID号："))
        self.xy.setPlaceholderText(_translate("zhuce1", "学院："))
        self.xb.setItemText(0, _translate("zhuce1", "男"))
        self.xb.setItemText(1, _translate("zhuce1", "女"))
        self.xm.setPlaceholderText(_translate("zhuce1", "姓名："))
        self.dh.setPlaceholderText(_translate("zhuce1", "电话："))
        self.lx.setItemText(0, _translate("zhuce1", "本科生"))
        self.lx.setItemText(1, _translate("zhuce1", "研究生"))
        self.lx.setItemText(2, _translate("zhuce1", "教授"))
        self.mm.setPlaceholderText(_translate("zhuce1", "密码："))
        self.pushButton2.setText(_translate("zhuce1", "退出"))

    def insert(self):
        usernumber=self.sm.text()
        username=self.xm.text()
        userschool=self.xy.text()
        userphone=self.dh.text()
        usersex=self.xb.currentText()
        userid=self.lx.currentText()
        password=self.mm.text()
        credeit = 2
        kj=0
        if self.lx.currentText() == '本科生':
           kj=10
        elif self.lx.currentText() == '研究生':
             kj=20
        elif self.lx.currentText() == '教师':
             kj=30
        sql1 = 'SELECT * FROM reader WHERE ID号="%s"' % usernumber
        res = cursor.execute(sql1)
        if res:
            QMessageBox.warning(self, "警告", "该读者ID已被占用！", QMessageBox.Yes)
        else:
            text = (usernumber,username,userschool,usersex,userid,userphone,kj,credeit,password)
            sql2 = 'insert into reader(ID号,姓名,学院,性别,读者类型,电话,可借册数,信用级别,password) values(%s,%s,%s,%s,%s,%s,%s,%s,%s)'
            cursor.execute(sql2,text)
            conn.commit()
            QMessageBox.warning(self, "提示", "注册成功！", QMessageBox.Yes)

    def exite(self):
        self.denglu1 = dengluui()
        self.denglu1.show()
        self.close()