# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhucegaunliyuan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem,QMessageBox
from denglu import Ui_MainWindow
from connect import *

cursor,conn=connect()

class dengluui(QtWidgets.QMainWindow,Ui_MainWindow):
    def __init__(self, parent=None):
        super(dengluui, self).__init__(parent)
        self.setupUi(self)

class Ui_zhuce3(object):
    def setupUi(self, zhuce3):
        zhuce3.setObjectName("zhuce3")
        zhuce3.resize(712, 524)
        zhuce3.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.zc = QtWidgets.QPushButton(zhuce3)
        self.zc.setGeometry(QtCore.QRect(250, 400, 221, 81))
        self.zc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.zc.setObjectName("zc")
        self.label = QtWidgets.QLabel(zhuce3)
        self.label.setGeometry(QtCore.QRect(60, 40, 251, 51))
        self.label.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(zhuce3)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 100, 613, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sm = QtWidgets.QLineEdit(self.layoutWidget)
        self.sm.setMinimumSize(QtCore.QSize(300, 40))
        self.sm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sm.setText("")
        self.sm.setObjectName("sm")
        self.verticalLayout.addWidget(self.sm)
        self.xm = QtWidgets.QLineEdit(self.layoutWidget)
        self.xm.setMinimumSize(QtCore.QSize(300, 40))
        self.xm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xm.setText("")
        self.xm.setObjectName("xm")
        self.verticalLayout.addWidget(self.xm)
        self.mm = QtWidgets.QLineEdit(self.layoutWidget)
        self.mm.setMinimumSize(QtCore.QSize(300, 40))
        self.mm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mm.setText("")
        self.mm.setObjectName("mm")
        self.verticalLayout.addWidget(self.mm)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.pushButton2 = QtWidgets.QPushButton(zhuce3)
        self.pushButton2.setGeometry(QtCore.QRect(570, 30, 111, 41))
        self.pushButton2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton2.setObjectName("pushButton2")

        self.retranslateUi(zhuce3)
        QtCore.QMetaObject.connectSlotsByName(zhuce3)
        self.zc.clicked.connect(self.insert)
        self.pushButton2.clicked.connect(self.exite)

    def retranslateUi(self, zhuce3):
        _translate = QtCore.QCoreApplication.translate
        zhuce3.setWindowTitle(_translate("zhuce3", "Form"))
        self.zc.setText(_translate("zhuce3", "注册"))
        self.label.setText(_translate("zhuce3", "<html><head/><body><p><span style=\" font-size:16pt; color:#ff0000;\">请输入相关的信息</span></p></body></html>"))
        self.sm.setPlaceholderText(_translate("zhuce3", "ID号："))
        self.xm.setPlaceholderText(_translate("zhuce3", "姓名："))
        self.mm.setPlaceholderText(_translate("zhuce3", "密码："))
        self.pushButton2.setText(_translate("zhuce3", "退出"))

    def insert(self):
        managernumber = self.sm.text()
        managername = self.xm.text()
        password = self.mm.text()
        sql = 'SELECT * FROM book_manager WHERE ID="%s"' % managernumber
        res = cursor.execute(sql)
        if res:
            QMessageBox.warning(self, "警告", "该管理员已经存在！", QMessageBox.Yes)
        else:
            sql1 = 'SELECT * FROM manager_registor WHERE ID="%s"' % managernumber
            res = cursor.execute(sql1)
            if res:
               QMessageBox.warning(self, "警告", "请勿重复发送！", QMessageBox.Yes)
            else:
               text = (managernumber, managername, password)
               sql2 = 'insert into manager_registor(ID,姓名,password) values(%s,%s,%s)'
               cursor.execute(sql2, text)
               conn.commit()
               QMessageBox.warning(self, "提示", "注册申请发送成功！", QMessageBox.Yes)

    def exite(self):
        self.denglu1 = dengluui()
        self.denglu1.show()
        self.close()



